### ISSUE TITLE
Namespaces mentioned in config file doesn't appear in content section though it appears in toc

### ISSUE THREAD

**Issue by selvakumar-invicara** [ur300/documentation-theme-light#15]
I have many namespaces which I would like to keep it in toc, So I have added them in .yml and generated the documentation with below comment,

`documentation build src/** -f html -o docs -c documentation.yml --theme node_modules/documentation-theme-light`

The namespaces I mentioned `documentation.yml` appears in toc. But when I click them I can't see the details.

**Comment by sponnusamy** [comment]
Please accept the PR and merge it https://github.com/ur300/documentation-theme-light/pull/16

Thanks

**Comment by ur300** [comment]
merged PR #16

**Comment by selvakumar-invicara** [comment]
Thanks ! Can you please publish this change

**Comment by ur300** [comment]
> Thanks ! Can you please publish this change

version 1.1.1 published
