### ISSUE TITLE
Theme doesn’t fit the screenshot

### ISSUE THREAD

**Issue by ai** [ur300/documentation-theme-light#5]
There are few big changes in current theme and screenshot

https://i.imgur.com/uBoatg9.png
https://i.imgur.com/w3nw6NP.png

1. There is a search field (I suggest to add it to screenshot)
2. Classes are collapsed by default (I think we should open it by default, buy it is an open question)
3. No left padding for classes members like `#stream` (I think we should add it)

**Comment by ur300** [comment]
fixed
