### ISSUE TITLE
Wrong element in the menu

### ISSUE THREAD

**Issue by ai** [ur300/documentation-theme-light#7]
After using Documentation.js with this theme on [audio-recorder-polyfill](https://github.com/ai/audio-recorder-polyfill/blob/master/index.js) I got 2 unknown `dispatchEvent` elements in the menu. Their link doesn’t go anywhere.

https://i.imgur.com/5iOzgrf.png

I created [branch](https://github.com/ai/audio-recorder-polyfill/tree/documentationjs) to reproduce the error.

1. Call `yarn api`
2. Open `test/demo/build/api/index.html`

**Comment by ur300** [comment]
these 2 events come from the following comments 
<img width="951" alt="Screen Shot 2019-05-02 at 19 25 23" src="https://user-images.githubusercontent.com/3381873/57090864-79b01d00-6d10-11e9-92ac-2984b03ff12b.png">
Seems these comments are just hints for developers and not supposed to be visible in docs. 
Maybe change them with `//`?

**Comment by ai** [comment]
Thanks. It fixed the problem.
