### ISSUE TITLE
Use <code> in code examples

### ISSUE THREAD

**Issue by ai** [ur300/documentation-theme-light#8]
I use [Yaspeller](https://github.com/hcodes/yaspeller) to protect JSDoc from spelling errors.

```json
  "scripts": {
    "spell": "yaspeller-ci *.md test/demo/build/api/*.html",
    "api": "documentation build -o test/demo/build/api/ -f html --theme node_modules/documentation-theme-light *.js",
    "test": "yarn api && yarn spell",
```

Unfortunately, code examples don’t wrap into `<code></code>` tags to prevent Yaspeller from checking the text. Right now theme uses only `<pre>`, which is not 100% semantic correct (we need `pre` and `code`).

https://i.imgur.com/ukP769X.png

As a result, I have spelling check errors for variable names from the code examples.

**Comment by ur300** [comment]
done
